### ISSUE TITLE
bus route numbers no longer appear in the pull-down menu

### ISSUE THREAD

**Issue by saulbaizman** [joeshaw/mbta-bus#2]
As of a couple days ago, the bus route numbers no longer appear in the pull-down menu. Instead, the route origins and destinations appear. Can both be visible like so?

…
87 — Clarendon Hill - Lechmere via Highland Avenue
88 — Clarendon Hill or Davis - Sullivan
90 — Davis - Wellington
…

![screen shot 2018-08-12 at 15 23 09](https://user-images.githubusercontent.com/4617523/44005605-ea5ede02-9e43-11e8-9f9f-1ac5d43f769f.png)

**Comment by joeshaw** [comment]
Thanks for bringing this to my attention, it's now fixed.
